# render.yaml for Render deployments
# Replace placeholders (names, plan, region, values) before using.

services:
  - type: web
    name: make-recipe-by-picture-web
    env: docker
    branch: main
    dockerfilePath: ./Dockerfile
    plan: starter # change to an appropriate plan if needed
    buildCommand: ""
    startCommand: 'sh -c "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"'
    envVars:
      - key: DATABASE_URL
        value: ""
        sync: false
      - key: OPENAI_API_KEY
        value: ""
        sync: false
      - key: S3_BUCKET
        value: ""
        sync: false
      - key: AWS_ACCESS_KEY_ID
        value: ""
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        value: ""
        sync: false
      - key: AWS_REGION
        value: ""
        sync: false

# Optional: create a managed Postgres instance via Render's infrastructure-as-code
databases:
  - name: make-recipe-db
    engine: postgres
    plan: starter # adjust as needed
    # region: "oregon" # uncomment and set region if you want to pin it
# Notes:
# - Fill the env var values in the Render dashboard or add them here (sensitive values
#   are better set in the Render UI as secrets rather than in the repo).
# - After pushing this file to your GitHub repo, connect the repo to Render.
#   Render will detect render.yaml and can create services/databases from it.
# - You can still configure / overwrite environment variables in Render's dashboard.
# - For production, consider adjusting the service 'plan' and database 'plan',
#   and enabling backups for the database.
